[
  { "word": "JANGLE", "clue": "What keys do in a pocket, and what nerves do after a Monday meeting (6)", "date": "2026-05-30" },
  { "word": "MUSTER", "clue": "Soldiers assemble; courage is gathered (6)", "date": "2026-05-31" },
  { "word": "WALNUT", "clue": "A wrinkled brain in a hard shell (6)", "date": "2026-06-01" },
  { "word": "DONKEY", "clue": "Works hard, complains loudly, gets no credit (6)", "date": "2026-06-02" },
  { "word": "PLANKS", "clue": "Pirates loved them. Gym bros also love them. For entirely different reasons (6)", "date": "2026-06-03" },
  { "word": "BUNKER", "clue": "Where golfers go to suffer, and where leaders go to hide (6)", "date": "2026-06-04" },
  { "word": "WISDOM", "clue": "What age supposedly brings, and teeth definitely don't (6)", "date": "2026-06-05" },
  { "word": "FROSTY", "clue": "The snowman, the reception, and the morning your car won't start (6)", "date": "2026-06-06" },
  { "word": "FERRET", "clue": "Searches relentlessly through everything — also an animal that smells while doing it (6)", "date": "2026-06-07" },
  { "word": "SIMMER", "clue": "What the soup does, and what you do when you're too polite to boil over (6)", "date": "2026-06-08" },
  { "word": "GROTTO", "clue": "A cave with pretensions (6)", "date": "2026-06-09" },
  { "word": "SQUINT", "clue": "What you do at small print, and at people you don't quite trust (6)", "date": "2026-06-10" },
  { "word": "NETHER", "clue": "Below, beneath, and somewhere you'd rather not be (6)", "date": "2026-06-11" },
  { "word": "JESTER", "clue": "The only person in the room allowed to tell the king he's wrong (6)", "date": "2026-06-12" },
  { "word": "URCHIN", "clue": "Found in rock pools and Victorian streets — equally difficult to handle (6)", "date": "2026-06-13" },
  { "word": "GRAVEL", "clue": "Sounds like it describes a rough voice, and also what's under your tyres (6)", "date": "2026-06-14" },
  { "word": "PLANET", "clue": "Blueprint and an alien make a world (6)", "date": "2026-06-15" },
  { "word": "LOCKET", "clue": "Curl of hair kept in a small prison (6)", "date": "2026-06-16" },
  { "word": "CANTER", "clue": "Not quite a gallop — hidden inside 'significant error' (6)", "date": "2026-06-17" },
  { "word": "KETTLE", "clue": "Britain's first responder in any crisis (6)", "date": "2026-06-18" },
  { "word": "SHADOW", "clue": "Loyal follower, gone by nightfall (6)", "date": "2026-06-19" },
  { "word": "BEACON", "clue": "Guiding light hidden in 'be a connoisseur' (6)", "date": "2026-06-20" },
  { "word": "ANCHOR", "clue": "Ends the relay, reads the news (6)", "date": "2026-06-21" },
  { "word": "CARROT", "clue": "The stick's gentler colleague (6)", "date": "2026-06-22" },
  { "word": "JIGSAW", "clue": "A picture you destroy on purpose, then spend a week regretting (6)", "date": "2026-06-23" },
  { "word": "RHYTHM", "clue": "What drummers keep and dad dancers lose (6)", "date": "2026-06-24" },
  { "word": "TEAPOT", "clue": "Short, stout, and full of strong stuff (6)", "date": "2026-06-25" },
  { "word": "REWARD", "clue": "Send the drawer back for the finder's fee (6)", "date": "2026-06-26" },
  { "word": "GOSSIP", "clue": "News with the boring parts removed (6)", "date": "2026-06-27" },
  { "word": "SPRING", "clue": "Season, coil, leap, water source — hardest-working word in English (6)", "date": "2026-06-28" },
  { "word": "OYSTER", "clue": "The world, apparently (6)", "date": "2026-06-29" },
  { "word": "TUNNEL", "clue": "Where the light at the end is, allegedly (6)", "date": "2026-06-30" },
  { "word": "BANTER", "clue": "Pub talk found in 'urban terrace' (6)", "date": "2026-07-01" },
  { "word": "MAGNET", "clue": "Attractive, yet repels half the people it meets (6)", "date": "2026-07-02" },
  { "word": "WICKET", "clue": "Three sticks defended all summer like national treasure (6)", "date": "2026-07-03" },
  { "word": "PIRATE", "clue": "Self-employed, at sea, flexible about ownership (6)", "date": "2026-07-04" },
  { "word": "CACTUS", "clue": "Survives neglect, resents affection (6)", "date": "2026-07-05" },
  { "word": "SONNET", "clue": "Love, rationed to fourteen lines (6)", "date": "2026-07-06" },
  { "word": "HICCUP", "clue": "Minor setback that repeats on you (6)", "date": "2026-07-07" },
  { "word": "QUIVER", "clue": "Arrow holder, what a new lover makes you do (6)", "date": "2026-07-08" },
  { "word": "COBWEB", "clue": "Vacant property, one previous owner, eight legs (6)", "date": "2026-07-09" },
  { "word": "PUZZLE", "clue": "You're doing one right now (6)", "date": "2026-07-10" },
  { "word": "GEYSER", "clue": "Sounds like an old man; erupts like one too (6)", "date": "2026-07-11" },
  { "word": "BRIDGE", "clue": "Card game, dental work (6)", "date": "2026-07-12" },
  { "word": "NAPKIN", "clue": "Lap armour, deployed at spaghetti (6)", "date": "2026-07-13" },
  { "word": "ABACUS", "clue": "Calculator, batteries not required since antiquity (6)", "date": "2026-07-14" },
  { "word": "YONDER", "clue": "Over there, but make it poetic (6)", "date": "2026-07-15" },
  { "word": "CANDLE", "clue": "Outshone by the lightbulb everywhere except birthdays (6)", "date": "2026-07-16" },
  { "word": "SECRET", "clue": "Everyone promises to keep it; nobody does (6)", "date": "2026-07-17" },
  { "word": "CASTLE", "clue": "The only building that's also a chess move (6)", "date": "2026-07-18" }
]
